#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_16FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_16FUNC_H

#include <stdbool.h>

int sumDigits(int n);

bool isTicketHappy(int ticket);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_16FUNC_H
