#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_1FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_1FUNC_H

double abs(double a);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_1FUNC_H
