#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_2FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_2FUNC_H

int sign(double x);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_2FUNC_H
