#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_3FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_3FUNC_H

int max2(int a, int b);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_3FUNC_H
