#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_4FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_4FUNC_H

#include "3func.h"

int max3(int a, int b, int c);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_4FUNC_H
