#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_5FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_5FUNC_H

#include <math.h>

double getDistance(int x1, int y1, int x2, int y2);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_5FUNC_H
