#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_7FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_7FUNC_H

#include <stdbool.h>

bool isDigit(int x);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_7FUNC_H