#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_8FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_8FUNC_H

void swap(float *a, float *b);

void intSwap(int *a, int *b);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_8FUNC_H
