#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_9FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_9FUNC_H

#include "8func.h"

void sort2(float *a, float *b);

void intSort2(int *a, int *b);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_6_9FUNC_H
