#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_UTILS_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_UTILS_H

int fcompare(double a, double b);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_UTILS_H
