#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_BUBBLESORT_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_BUBBLESORT_H

#include <stddef.h>

#include "../tester.h"

SortFunc getBubbleSFunc();

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_BUBBLESORT_H
