#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_COMBSORT_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_COMBSORT_H

#include <stddef.h>

#include "../tester.h"

SortFunc getCombSFunc();

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_COMBSORT_H
