#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_INSERTIONSORT_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_INSERTIONSORT_H

#include <stddef.h>

#include "../tester.h"

SortFunc getInsertionSFunc();

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_INSERTIONSORT_H
