#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_SELECTIONSORT_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_SELECTIONSORT_H

#include <stddef.h>

#include "../tester.h"

SortFunc getSelectionSFunc();

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_SELECTIONSORT_H
