#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_SHELLSORT_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_SHELLSORT_H

#include <stddef.h>

#include "../tester.h"

SortFunc getShellSFunc();

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_SHELLSORT_H
