#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_4FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_4FUNC_H

void invertHex(unsigned long long *x);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_4FUNC_H
