#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_5FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_5FUNC_H

#include <stdbool.h>

bool isBinPoly(unsigned long long x);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_5FUNC_H
