#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_6FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_6FUNC_H

#include <stdint.h>

uint32_t getEvenOddCombination(uint16_t sh1, uint16_t sh2);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_6FUNC_H
