#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_8FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_8FUNC_H

void cycleShift(unsigned long long *pX, int k);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_8FUNC_H
