#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_9FUNC_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_9FUNC_H

unsigned long long removeEverySecondDigit(unsigned long long x);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_7_9FUNC_H
