#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_GENERATERANDOM_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_GENERATERANDOM_H

#include "../tester.h"

void generateRandom(int *a, size_t n);

GeneratingFunc getRandomGFunc();

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_GENERATERANDOM_H
