#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_GENERATEORDEREDBACKWARDS_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_GENERATEORDEREDBACKWARDS_H

#include <stddef.h>

#include "../tester.h"

void generateOrderedBackwards(int *a, size_t n);

GeneratingFunc getOrderedBackwardsGFunc();

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_GENERATEORDEREDBACKWARDS_H
