#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_GETWORDALTERNATION_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_GETWORDALTERNATION_H

#include "revertEveryWord.h"

void getWordAlternation(char *s1, char *s2, char *destination);

void test_getWordAlternation();

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_GETWORDALTERNATION_H
