#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_REMOVENONLETTERS_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_REMOVENONLETTERS_H

#include "../string_.h"

void test_removeNonLetters();

void removeNonLetters(char *s);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_REMOVENONLETTERS_H
