#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_REMOVEEXTRASPACES_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_REMOVEEXTRASPACES_H

#include "../string_.h"

void test_removeExtraSpaces();

void removeExtraSpaces(char *s);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_REMOVEEXTRASPACES_H
