#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_REPLACEDIGITSBYSPACES_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_REPLACEDIGITSBYSPACES_H

#include "../string_.h"

void replaceDigitsBySpaces();

void test_replaceDigitsBySpaces();

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_REPLACEDIGITSBYSPACES_H
