#ifndef PROGRAMMING_AND_ALGORITHMIZATION_BASICS_TASKS_H
#define PROGRAMMING_AND_ALGORITHMIZATION_BASICS_TASKS_H

void solveSquareEquation(float a, float b, float c, float *x1, float *x2);

#endif //PROGRAMMING_AND_ALGORITHMIZATION_BASICS_TASKS_H
